AWSTemplateFormatVersion: "2010-09-09"
Description: API Rest
Resources:
  Ec2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0022f774911c1d690
      KeyName: api-rest  # criar uma chave de nome api-rest
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
